version: 2.1
jobs:
  build:
    docker:
      - image: cimg/clojure:1.11.1
    steps:
      - checkout
      - run:
          name: "Build uberjar"
          command: |
            lein uberjar
      - setup_remote_docker:
          version: 20.10.22
      - run:
          name: "Build docker image"
          command: |
            docker build -t iamedu-backend .
      - store_artifacts:
          path: target/iamedu-backend-0.0.1-SNAPSHOT-standalone.jar
